- adi/ad9361.py
- adi/attribute.py
- test/test_pluto_attr.py
> Add loopback mode to AD9361 with tests

- adi/dds.py
- adi/rx_tx.py
- doc/source/buffers/index.rst
- examples/adrv9009_som.py
- test/test_ad9361.py
- test/test_daq2.py
- test/test_pluto.py
PR addresses random order DDS channels can be looped through. DMA testing has been added to validate buffers transfers which addresses #12
> DDS fixes and buffer updates

- requirements_dev.txt
- setup.cfg
- test/iio_scanner.py
- test/test_ad9144.py
- test/test_ad9361.py
- test/test_ad9680.py
- test/test_adis16460_attr.py
- test/test_daq2.py
Add automatic device search for HW tests
> HW Test updates

- adi/rx_tx.py
- test/test_pluto.py
> Add cyclic buffer helper functions and related tests

- adi/dds.py
- doc/source/fpga/index.rst
- examples/daq2.py
- test/test_ad9361.py
- test/test_daq2.py
- test/test_pluto.py
PR updates DDS API with helper functions. This includes tests for the API and examples with DAQ2 using the API.
> DDS update

- .travis.yml
> Cleanup CI stages and fix #14

- .travis.yml
> Force CI to not cleanup built doc which prevented deployment

- adi/rx_tx.py
> Add docstrings for rx and tx methods

- adi/ad5627.py
- adi/ad9094.py
- adi/fmclidar1.py
- examples/lidar.py
Add device ad9094
Add device ad5627
Add Lidar which uses both devices from above and also configures 'pulse-capture'
Add Lidar GUI example
> (WIP) Add Lidar

- adi/dds.py
> Remove init for DDS class

- adi/ad9094.py
- adi/fmclidar1.py
- examples/lidar.py
Add auto mode in the fmclidar to enable support for reading all the 16 channels.
Handle the received buffer as int8 by default.
Update the example GUI to display all the channels and all the distance measurements for each channel, add more config parameters and use a generated reference signal instead of the reference signal received from the board.
> Lidar Update

- adi/ad936x.py
- adi/fmcomms5.py
- examples/fmcomms5.py
PR fixes AD936x related issues on secondary chip channels
> Ad936x fixes

- test/iio_scanner.py
> Add fix for local context which syntax was untested before

- adi/__init__.py
> Add fmclidar1 to other imports

- .isort.cfg
> Add isort config to help with IIO precommit checks

- test/rf/phase.py
- test/rf/test_phase.py
> Add phase estimates and tests to core measurements

- adi/ad9371.py
> Update doc for AD9371

- doc/source/dev/index.rst
- doc/source/index.rst
- test/conftest.py
- test/iio_scanner.py
PR adds initial test configuration from yaml which is very handy for CI and generally development. Included is also doc for developers who would use these config files, along with other details for developers on tools.
> Add test configuration and related doc

- README.md
> Fix README link to supported parts

- adi/adrv9009.py
- adi/adrv9009_zu11eg.py
- examples/adrv9009_som_fhm_phase.py
- examples/adrv9009_som_sync.py
Enhance ADRV9009 and SOM variant with sync methods. An example with FHM and sync is included.
> ADRV9009 + ADRV9009-ZU11EG Sync

- test/test_ad9364_p.py
> Add pluto label to ad9364 tests

- test/test_map.py
> Fix test mapping around AD936x tests

- test/conftest.py
- test/test_ad9361_p.py
- test/test_generic.py
- test/test_pluto_p.py
- test/test_stress.py
> Add stress tests for buffers and contexts

- test/common.py
- test/conftest.py
- test/globals.py
conftest.py was becomming unmanagable so this PR splits it into more logical components.
* Hardware: ADRV9361 + PlutoSDR
> Split of test files

- test/conftest.py
Fix Import in certain test cases.
> Add missing import for testing

- adi/ad9371.py
- examples/ad9371_dec8.py
- test/conftest.py
- test/test_ad9371.py
This PR update the AD9371 interfaces and adds testing for various settings and the data paths
* Hardware: ADRV9371+ZCU102
* OS: 2019 R1+Ubuntu 18.04
> Ad9371 filter

- adi/ad7124.py
This fixes the buffered capture of the AD7124.
> Ad7124: fix buffered capture

- examples/adiplot.py
- examples/requirements_adiplot.txt
Adds an example with pyqtgraph to fancy visualization
> Add pyqtgraph example for AD936x

- adi/adar1000.py
Fix code format issues with ADAR1000. Travis-CI was down and this slipped through.
* Hardware: Raspberry PI + EZ-ADAR1000
> Fix formatting for ADAR1000. Missed when CI was down.

- adi/adrv9009_zu11eg_multi.py
Fix formatting from PR with CI enabled.
> Fix formatting in ADRV9009 SOM class

- test/test_ad9364_p.py
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
* Hardware:
* OS:
> test/test_ad9364_p.py: Fix typos

- README.md
Fix README to point to correct doc and new GH CI.
> Update README for GH CI and fix link

- supported_parts.md
- tasks.py
Update supported parts doc and precommit checks.
> Update supported parts doc and checks

- adi/ad9081.py
- examples/ad9081_example.py
- examples/pluto.py
- test/common.py
- test/conftest.py
- test/dma_tests.py
- test/test_ad9081.py
This fixes a few obvious issues in some untested code 
* Hardware:
* OS:
> Ad9081 support fixes

- adi/adrv9009_zu11eg_multi.py
This PR fixes a minor issue when there is a _pre_setup exception in the ADRV9009 Multi-SOM class.
> Fix ADRV9009-SOM multi bug

- adi/rx_tx.py
- doc/source/buffers/index.rst
- test/conftest.py
- test/dma_tests.py
- test/test_pluto_p.py
Fixes #163 and adds more features related to buffers.
New tests have been added to validate new zeroing buffer features which are part of PR.
* Hardware: PlutoSDR
Doc has been updated in regards to the new behavior.
> Empty enable chan

- adi/adar1000.py
> Fix docstring warnings for ADAR1000

- examples/adiplot.py
> Add support for CN0532 to ADIPlot app

- adi/ad9081.py
- examples/adiplot.py
- setup.cfg
This PR adds PFILT support to AD9081 classes.
Manually tested with AD9081+ZCU102.
* Hardware: AD9081+ZCU102
> Add pfilt API to AD9081

- doc/source/dev/index.rst
Add documentation about using isolated development environments.
> Add documentation to show isolated install setup

- examples/adrv9009_som_multi.py
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
This patch adds the option to use this example without FMCOMMS8 attached.
Using the ADRV9009-ZU11EG Boot Files from here
https://wiki.analog.com/resources/eval/user-guides/adrv9009-zu11eg/syncronization#software
* Hardware:
* OS:
> examples/adrv9009_som_multi.py: Make FMCOMMS8 optional

- adi/ad9081_mc.py
This fixes a few issues and adds a new feature  found on the multi-device instantiation of the AD9081 
> Fix quadmxfe

- adi/ad7606.py
- adi/ad9371.py
- adi/sshfs.py
- test/common.py
- test/conftest.py
- test/test_ad7606.py
- test/test_sshfs.py
> Fix formatting from PRs

- adi/ad9136.py
- test/test_ad9136_p.py
Signed-off-by: Liam Beguin <lvb@xiphos.com>
This was tested using the `jesd_statuses`.
**Test Configuration**: tested on a custom daughterboard and a ad9144-fmc-ebz
* Hardware: ZynqMP and ad9144-fmc-ebz
* OS: Linux
This is based on the ad9144
> add initial support for the ad9136 DAC

- adi/ad9136.py
Fix minor build issue that propagates in unrelated branches/PRs.
Example: https://github.com/analogdevicesinc/pyadi-iio/tree/adpd410x
Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>
> ad9136: minor build fix

- adi/cn0540.py
> Add device attribute for sample rate for CN0540

- requirements_dev.txt
- test/conftest.py
- test/dma_tests.py
- test/html.py
- test/plot_logger.py
- test/rf/spec.py
PR adds support for the generation of HTML reports with embedded plots. This will feed some of the Jenkins HTML publishers.
> Add support for HTML reports with built in plots for testing

- adi/adrv9009_zu11eg.py
- adi/adrv9009_zu11eg_fmcomms8.py
- adi/adrv9009_zu11eg_multi.py
- adi/sshfs.py
- examples/adrv9009_som_single_sync.py
This is a fixed bag of commits.
> Zu11eg single sync

- adi/adrv9009_zu11eg.py
- adi/adrv9009_zu11eg_fmcomms8.py
- adi/sshfs.py
- examples/adrv9009_som_single_sync.py
> Fix linter issues

- .github/workflows/test.yml
> Enable CI on PRs

- adi/cn0540.py
Update CN0540 base to use new GPIO naming for SW-CC. 
> Update cn0540 sw cc

- examples/adrv9002_example.py
> Update gain control mode in ADRV9002 example to be within range for default profiles

- setup.py
> Pin libiio bindings requirement

- test/conftest.py
- test/dma_tests.py
- test/test_pluto_p.py
This PR adds underflow/overflow checking for Pluto but the tests should be generic enough for others.
* Hardware: ADALM-PLUTO
Tests will get included in autogenerated doc.
> Add overflow/underflow tests

- test/scpi.py
Signed-off-by: Ramona Alexandra Nechita <ramona.nechita@analog.com>
The tuning parameters from the calibration weren't save anywhere previously, therefore two utility functions for loading and saving to eeprom were added.
* Hardware: ADRV9361-ZC702
> Add load/save to eeprom functionality for tuning parameters.

- adi/rx_tx.py
Fixes #224 
**Test Configuration**: pytest test_ad9361_p.py
* Hardware: ADRV9361-Z7035
> Fix multi-buffer error

- setup.py
> Bump libiio version dependency to v0.23

- adi/ad9083.py
adi/ad9083.py: 
- AutoGen channel list and determine complex mode
- Support for NCO0, NCO1 and NCO2 frequency
- Add support for rx_sample_rate and direct reg access
Tested on HW
> AD9083 updates

- test/test_generic.py
Fixes AD9361 generics tests.
* Hardware: ADRV9361+FMC
> Fix AD9361 generic tests

- adi/rx_tx.py
Fix Windows cleanup error.
Fixes #248 
* Hardware: AD9081+ZCU102
* OS: Windows 10+Python 3.7
> Fix #248 buffer destructor error

- doc/source/libiio.md
- test/test_adrv9002_p.py
> Add reg read/write to doc

- .github/workflows/test.yml
> Add JUnit logging for tests

- doc/source/conf.py
- requirements_doc.txt
> Switch doc theme to furo

- .github/workflows/test.yml
> Add doc deploy for master branch

- .github/workflows/test.yml
> Switch packaging to use build to generate wheel

- README.md
- adi/adar1000.py
- adi/adf4371.py
- adi/adrv9009.py
- adi/adrv9009_zu11eg_multi.py
- adi/fmcomms5.py
- adi/jesd.py
- adi/one_bit_adc_dac.py
- adi/sshfs.py
- doc/source/index.rst
> Codacy fixes

- .github/workflows/test.yml
- .github/workflows/win-test.yml
- test/test_map.py
> Add Windows CI Conda support

- .github/workflows/doc.yml
- adi/dds.py
- doc/source/conf.py
- doc/source/devices/index.rst
- doc/source/index.rst
- tasks.py
Add CI checks for documentation that covers
- Build checks
- Coverage
- Listed parts
- Links
This also includes fixes for certain found doc errors.
> Doc checks

- doc/source/index.rst
> Fix code block on index

- doc/source/dev/index.rst
> Add doc around emulation testing

- examples/cn0548/CN0548_simple_plot.py
This is a sample application script that allows data logging and plotting for the CN0548.
The CN0548 board was mounted on an ADICUP3029 with a preloaded hex file to collect data from ad7798/ad7799. The setup is connected to a host PC via USB to microUSB cable. Multiple runs were then made in order to test out the different board configurations and combinations of active software features. There are 4 different gathering modes from the onboard  jumper configurations and 6 possible sets of active software features when the script is activated. All of these cases were tested by allowing the board to continuously run for almost an hour then checking whether the activated features worked accordingly. Features: plotting, data logging, config memory
* Hardware: CN0548, …
> Added data logging and plotting script for CN0548 in the examples folder

- .github/workflows/test.yml
> Limit coverage test publication to not pull requests

- .github/workflows/test.yml
- requirements_dev.txt
- test/test_generic.py
> Fix failing CI tests

- .github/workflows/test.yml
- examples/ad9081_register_dump.py
> Add AD9081 register dump example

- adi/ad9371.py
- requirements_dev.txt
- test/test_ad9144_p.py
- test/test_ad9152_p.py
- test/test_ad9361_p.py
- test/test_ad9680_p.py
- test/test_all_inits.py
- test/test_daq2_p.py
- test/test_daq3_p.py
- test/test_fmcomms5_p.py
- test/test_pluto_p.py
- test/test_stress.py
> Fix emu tests

- .codespell-whitelist
- adi/tdd.py
- doc/source/devices/adi.tdd.rst
- doc/source/devices/index.rst
- examples/ad9081_tdd_example.py
This PR adds a [TDD Controller](https://wiki.analog.com/resources/fpga/docs/axi_tdd) class and accompanying example.
* Hardware: AD9081 on ZCU102 with TDD controller
* OS: Linux, with recent software
> Add TDD controller class and example

- doc/source/devices/adi.tdd.rst
This PR fixes an absolutely minor copy/paste documentation issue i missed ...
> Fix header in TDD docs

- examples/cn0548/CN0548_simple_plot.py
UI has been simplified for end-users. Less prompts needed from the user to configure the application script. Board rework was also taken into consideration. Raw ADC code is now read from the board instead of pre-computed values. Computation takes place in the python script allowing higher data resolution.
Same as previous
A simple resistive circuit was used to produce a constant current. Voltage was probed across the load and the current flow was measured as well. This was done for all the 5 different voltage gains and 2 different input modes (10 configs in total)
* Hardware: CN0548, ADICUP3029, Host PC
* OS: Windows
You may refer to the wikipage: https://wiki.analog.com/resources/eval/user-guides/circuits-from-the-lab/cn0548#eval-cn0548-ardz_shield_overview
> CN0548 Sample Script Revision

- .github/workflows/test-pypi.yml
- MANIFEST.in
- setup.cfg
Add deploy for test-pypi on master and include manifest for packaging.
> [CI] tfcollins/packaging

- .github/workflows/test-pypi.yml
- tasks.py
> [CI] Add task for bumping development version

- .github/workflows/test-pypi.yml
- .github/workflows/test.yml
- README.md
- adi/ad9136.py
- adi/ad9371.py
- adi/adrv9009.py
- adi/adrv9009_zu11eg_multi.py
- adi/jesd.py
- adi/jesd_internal.py
- doc/update_devs.py
- setup.py
- test/conftest.py
- test/test_fmcomms2-3_prod.py
> Make SSH optional

- adi/QuadMxFE_multi.py
- adi/ad9081.py
- adi/adrv9009_zu11eg_multi.py
- adi/rx_tx.py
- adi/sync_start.py
- examples/ad9081_sync_start_example.py
Support for the new EXT_SYNC sync start HDL core feature
> Dev sync start

- adi/dds.py
- test/test_ad9680_p.py
- test/test_daq2_p.py
> Fix DAQ2 tests to handle 2019-R2+Newer builds

- Makefile
> Add makefile similar to pyadi-jif

- adi/cn0532.py
- adi/cn0540.py
> [cn0540] Update calibration routine

- examples/cn0549/collect_data.py
> Add calibration step to CN0549 example

- adi/rx_tx.py
> Add byte file generation support for iio_writedev

- .pre-commit-config.yaml
Fixes upstream bug: https://github.com/psf/black/issues/2964
> Pin click version in precommit for black

- doc/source/buffers/index.rst
- doc/source/fpga/index.rst
- doc/source/guides/connectivity.rst
- doc/source/guides/examples.rst
- doc/source/guides/quick.rst
> Minor doc tweaks

- adi/__init__.py
- adi/ad717x.py
- doc/source/devices/adi.ad717x.rst
- doc/source/devices/index.rst
- examples/ad717x_example.py
- supported_parts.md
- test/test_ad717x.py
1) Added ad717x.py with supported parts and attributes
2) Added an example script for ad717x
3) Added a test script
4) Updated supported_parts.md
5) Updated __init__.py
6) Added adi.ad717x.rst
Signed-off-by: Janani Sunil <Janani.Sunil@analog.com>
* Hardware: EVAL-AD4111SDZ with the SDP-K1 board
* OS: Windows 10
If this is a new feature or example please mention or …
> Added support for AD717x-AD411x family of devices

- JenkinsfileHW
Signed-off-by: Paller <KimChesed.Paller@analog.com>
Update JenkinsfileHW: set docker host mode to true
* Hardware:
* OS:
> Update JenkinsfileHW: set docker host mode to true

- JenkinsfileHW
<local_jenkins_server>/jenkins/job/Misc/job/test_pyadi_iio_testing/job/tfcollins%252Fjenkinshw/
* Hardware:
* OS:
> Fix docker container args and test artifacts logging issues

- JenkinsfileHW
Add Jenkinsfile for hardware testing
> Add Jenkinsfile for Hardware tests

- test/test_adrv9009_zu11eg.py
Signed-off-by: Bogdan Togorean <bogdan.togorean@analog.com>
- [ x ] Bug fix (non-breaking change which fixes an issue)
> Add missing parameter for test_gain_check

- adi/ad936x.py
- adi/dsp.py
- doc/update_devs.py
> Add generic support for enabling int8 and dec8 fpga filters

- .gitignore
- doc/source/_static/css/style.css
- doc/source/conf.py
Change doc sidebar to look nicer
> Update doc sidebar to look better

- requirements_doc.txt
> Add pillow to doc reqs

- adi/fmcomms5.py
> Fix gain control check for FMComms5

- JenkinsfileHW
> Enable all hardware for testing

- doc/source/_static/css/style.css
- doc/source/conf.py
- doc/source/index.rst
> Update doc index page to handle light/dark themes better

- adi/fmcomms5.py
> [Fix] FMComms5 add MCS calls to all sample rate changes

- JenkinsfileHW
- test/test_fmcomms5_p.py
This PR finally address the weird issues with FMComms5 testing. More MCS is the key here
* Hardware: ZC706+FMComms5
> Hw staging/enable libad9361

- test/test_daq3_p.py
Signed-off-by: Hannah Rosete <Hannah.Rosete@analog.com>
This addresses the failing pytests on our daily builds
Jenkins build: http://10.116.171.86/jenkins/blue/organizations/jenkins/HW_tests%2FHW_pyadi_test/detail/HW_pyadi_test/216/pipeline/496
> Edit test_daq3_p.py's peak_min to -50dB

- adi/rx_tx.py
Reorganize RX buffer to not interleave and then deinterleave constantly
> Reorg rx buffering

- adi/ad4110.py
- adi/ad4630.py
- adi/ad5686.py
- adi/ad9094.py
- adi/adis16460.py
- adi/adis16495.py
- adi/adis16507.py
- adi/adpd1080.py
- adi/adpd188.py
- adi/adxl355.py
- adi/cn0540.py
- adi/ltc2499.py
- adi/max11205.py
- adi/rx_tx.py
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com># Description
Fixes # (issue) - 
https://ez.analog.com/sw-interface-tools/f/q-a/562754/ad7124_simple_capture-py-does-not-find-ad7124-device
- AD7124 test program - generate sine from ADALM2000 into ad7124 - test with attached test program
> rx_tx: convert format dynamically per channel basis

- adi/ad7124.py
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
> ad7124: fix syntax error

- test/test_fmcomms5_p.py
> Add libad9361 checks to FMComms5 testing

- .github/workflows/doc.yml
- .github/workflows/test-pypi.yml
- .github/workflows/test.yml
- .github/workflows/win-test.yml
- README.md
- setup.py
- supported_parts.md
Signed-off-by: Collins <Travis.Collins@analog.com>
> Deprecate python 3

- doc/source/guides/quick.rst
> Add reference to conda doc

- adi/ad7606.py
1. Added ad7606c family devices
2. Corrected typo in 'channels' attribute naming
Signed-off-by: MPhalke <mahesh.phalke@analog.com>
Typo correction and addition of new devices
Tested with no-os drivers on SDP-K1 MCU platform using IIO client and server
* Hardware:
* OS:
> ad7606 drivers improvements

- README.md
- doc/source/index.rst
> Fix GH actions build badge

- README.md
- doc/source/guides/quick.rst
> Update README and doc to remove usage of setup.py

- CONTRIBUTING.md
Add contributions.md file based on libiio one.
> Add contributions guidelines

- .github/workflows/test-pypi.yml
> Fix GH Action for pypi testing

- pyproject.toml
> Add content type for readme

- .github/workflows/cleanup.yml
Add cleanup workflow for GHA for doc generation
> Add initial GH workflow to manage built development doc

- test/test_adxl355.py
- test/test_map.py
Added adxl355, adt7420 and cn0511 to test map. Includes a typo fix to test_adxl355.
No changes in documentation.
> Add adxl355, adt7420 and cn0511 to test map

- test/test_ad9081.py
Fix updates AD9081 to dynamically scale with actual properties available
* Hardware: AD9081-ZCU102
* OS: Ubuntu 22.04
> [FIX] Update AD9081 to support configuration variations

- pyproject.toml
Update pylibiio dep to fix issue with Apple Silicon.
Fixes #462 
> Update pylibiio dep to fix #462

- test/test_ad9081.py
Update implementation of recent fix for AD9081 test.
* Hardware: AD9081-ZCU102
* OS: Windows 10
> Update AD9081 scale_field method to trim parameter list

- JenkinsfileHW
This PR includes updates on the JenkinsfileHW needed for the test harness.
* Hardware:
* OS:
> Jenkinsfile update

- .github/scripts/install_libiio.sh
Fix libiio builds to use v0.25
> Change libiio CI branch to v0.25

- doc/source/guides/quick.rst
As per request by Debian users, PR updates doc to reference virtual environments.
> Add doc for virtual env installs

- adi/ad4630.py
- examples/ad4630/ad4630_example_all_mode.py
- examples/ad4630/ad4630_example_simple_plot.py
- test/test_ad4630.py
Updated ad4630 class, examples, and test to reflect changes that was applied in driver. 
> ad4630: updates on class, test, examples

- adi/ad5754r.py
- examples/ad5754r_example.py
1. Update driver to support additional attributes defined in the firmware
2. Remove typos from the example script
3. Update example script to demonstrate use of the dac attributes
* Hardware: SDP-K1, EVAL-AD5754REBZ
* OS: ad5754r iio firmware application running on SDP-K1; Python 3.7 on Windows 10
> Ad5754r update driver and examples

- examples/QuadMxFE_dual_example.py
- examples/QuadMxFE_example.py
- examples/QuadMxFE_ffh_example.py
- examples/Triton_example.py
Fixes for Quad/MxFE/Apollo examples
> Fix incorrect use of tx_enabled_channels

- examples/phaser/RADAR_FFT_Waterfall.py
Updates to various parameters, some refactoring.
Tested on phaser hardware by Jon Kraft
* Hardware: Phaser with Raspberry Pi 4
* OS: Kuiper Linux 2021_R2 on Pi, Windows 10 on remote host
N/A
> Update RADAR_FFT_Waterfall.py example

- adi/ad9081.py
- adi/ad9081_mc.py
- adi/ad9084.py
- adi/ad9084_mc.py
- adi/rx_tx.py
This change fixes some issues with the static behavior of the AD908X channel name properties
> Fix AD908X static props

- doc/source/_static/css/style.css
- doc/source/conf.py
- doc/source/index.rst
Fix some doc spacing and add optional deps
> Minor doc fixes

- test/test_adrv9009_p.py
- test/test_adrv9009_zu11eg.py
- test/test_adrv9009_zu11eg_fmcomms8.py
- test/test_map.py
Update test mapping for ADRV9009-ZU11EG
> Enable more tests for ADRV9009-SOM

- adi/ad5592r.py
- doc/source/devices/adi.ad5592r.rst
- doc/source/devices/index.rst
> Doc enhancements for AD5592r and index of parts

- adi/adrv9009.py
> fix profile write ADRV9009

- .github/workflows/doc.yml
- .github/workflows/test.yml
> Update Doc CI to python 3.8

- requirements_doc.txt
> Updat sphinx requirements

- adi/adis16475.py
adi: adis16475: Add support for adis1657x
* Hardware:
* OS:
> adi: adis16475: Add support for adis1657x

- adi/ad4630.py
Fixes #534 (issue)
* Hardware:
* OS:
> adi:ad4630.py: fix rx

- doc/source/conf.py
> Add adi-doc theme specific config

- examples/ad9467.py
> Remove pluto from AD9467 example

- test/conftest.py
The change includes removal of the pytest xml property with test docstring and adding new properties for test function name and test function module.
* Hardware:
* OS:
> Update pytest hook in conftest.py

- doc/source/devices/adi.ad9084.rst
> Fix AD9084 doc title

- adi/compat.py
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com># Description
* Hardware: AD-PQMON-SL, ADALM-PLUTO
* OS: Ubuntu 24.04
> adi: add support for big endian rx buffers

- test/test_map.py
> Add zynqmp_adrv9009_zu11eg_revb_adrv2crr_fmc_revb-sync-fmcomms8 in test map

- doc/source/guides/quick.rst
Explain the behavior on the visibility of iio, emphasizing on venvs.
* Hardware:
* OS:
> doc: add --system-site-packages, extend description

- .github/workflows/test.yml
> Enable back code coverage on EMU
