analogdevicesinc/pyadi-iio

- adi/ad9361.py
updated sample rate setter to match behavior in ad9361_baseband_auto_rate.c.  Allows Pluto to go down to 521kHz (couldn't go lower than around 2.5MHz prior).  I tested it by tuning to the FM band and "zooming" in and out, and it seemed to work fine, but it wasn't a comprehensive test.
> ad9361: sample rate setter

- adi/ad9361.py
- adi/ad9371.py
- adi/adrv9009.py
- adi/adrv9009_zu11eg.py
- test/test_ad9361.py
- test/test_adis16460_attr.py
Fix some string attribute writes which were broken in some of the new type-specific APIs. Added test to catch this case for gain control
> String attribute fixes

- adi/ad7124.py
- adi/adis16460.py
- adi/rx_tx.py
- examples/ad7124.py
- examples/adis16460
The AD7124 driver still has some issues, however this should be the API.
A few notes:
- Currently it only works when one channel is enabled.
- There are sample rates for all channels (and they are not shared attributes), however i'm not sure how it is supposed to work when having multiple channels enabled - same buffer, multiple rates. This is why I set the sample rate for all channels
- The scale and scale_available attribute was trickier because the str(float val) gives a value like 4.56+e06 which is incompatible with IIO.
- I'm not sure where the to_volts method should be implemented as it uses different coeficients for different channels.
- I created the channels list on __init__ dynamically. I do this because the number of channels is reconfigurable via devicetree. Does it make sense …
> Add support for AD7124

- .travis.yml
- README.md
- setup.py
PR explicitly sets supported python versions (3.6+)
> Add other python versions to ci

- adi/adxl345.py
- examples/adxl345_example.py
AD7124: Add type annotation to pass mypy
Revert AD7124 changes
Update to use rx(), remove to_g function
read out raw attribute
Signed-off-by: mark thoren <mark.thoren@analog.com>
> Add ADXL345 support

- adi/ad9371.py
- adi/obs.py
Add core components for observation channels and updated AD9371 class to
add this feature. This includes an additional attribute for the
observation path which is required to get data for the AD9371
specifically.
> Add observation buffered channel support

- adi/__init__.py
- adi/ltc2983.py
- examples/ltc2983.py
This patch adds support for the multi-sensor temperature measurement IC [LTC2983](https://www.analog.com/en/products/ltc2983.html).
Heavily inspired by the AD7124 interface. AFAICT, there's no buffer support for LTC2983 but I nevertheless kept support for it in the interface (`rx` subclass).
Also includes very minimal examples, very hardware dependent.
Thanks for your time!
> Add support for LTC2983

- adi/adrv9009.py
Profile loading was previously failing over ethernet, extending the
timeout fixed this issue
> Enable profiles for adrv9009

- tasks.py
Add common task automation for development through invoke. Currently supported tasks:
```
invoke --list
Available tasks:
build           Build python package
builddoc        Build sphinx doc
changelog       Print changelog from last release
checkparts      Check for missing parts in supported_parts.md
createrelease   Create GitHub release
libiiopath      Search for libiio python bindings
precommit       Run precommit checks
setup           Install required python packages for development through pip
test            Run pytest tests
```
> Add Invoke tasks file

- test/conftest.py
- test/iio_scanner.py
Changes:
1. Added a --uri parameter for pytest to target specific boards.
2. Do the ignore_skip checking if check_dev fails. So if check_dev fails, it either skips or fail(if --error_on_filter is passed).
Usage:
1. On specific test file:
pytest <test_filename> --uri=< uri of board >
e.g.:
pytest test/test_pluto_p.py --uri=ip:192.168.2.2
This should execute tests normally.
2. All tests:
pytest --uri=< uri of board >
e.g.:
pytest --uri=ip:192.168.2.2
This should skip all the tests that uses a device name that does not match the device name of the Context created from 192.168.2.2. This is the IP of pluto in this case so, only the Pluto related tests will be executed.
You can also use --error_on_filter with --uri. So, instead of skipping, tests that does not match the board pointed by the uri …
>  Added URI argument to use specific board in the pytest.

- test/conftest.py
- test/test_map.py
Add markers to each test function based on mapping to HDL project
variations. This allows simple filters of specific tests for specific
HDL projects.
> Add testing markers

- test/test_map.py
Organize and update board markers including specific ones for pluto.
> Update test board map

- adi/adrv9009_zu11eg_fmcomms8.py
Extend SOM support to include FMComms8. This includes overrides for
the synchronization features to support four chips.
> Add ADRV9009-ZU11EG + FMCOMMS8 Support

- adi/adis16507.py
- examples/adis16507_example.py
This attribute was removed from the driver. Burst mode is just used by
default.
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
> adis16507: Remove burst_mode_enable

- adi/ad936x.py
An improved __repr__ for the adi.Pluto() object.
Now gpg signed.
> Extended __repr__ of Pluto object

- test/test_ad9361_p.py
Fix broken attribute test for tx hardware gain of AD936x classes.
All AD9361 tests pass in hardware harness.
* Hardware: ADRV9361-Z7035
No documentation changes needed.
> Fix AD9361 gain test

- test/conftest.py
- test/test_ad9361_p.py
Fixed test ranges in randomized testing and add generic label for AD9361 tests for other devices.
* Hardware: ADRV9361-(BOB and FMC)
> Fix AD9361 test ranges and add AD9361 label for generic boards

- .pre-commit-config.yaml
- adi/adrv9009.py
This fixes profiles loading when multiple adrv9009 chips are available in a context.
Fixes #113 
* Hardware:ADRV9009-ZU11EG+FMComms8
* OS: 2019_R1 release + custom kernel with updated JESD framework
> Adrv9009 multi profile

- test/test_map.py
Update the testing map to not allow ad9364 tests for ad9361. This will fixed skipped tests that appear for AD9361 based devices.
> Update testing map to not allow ad9364 tests for ad9361

- adi/adar1000.py
Fixes issues where drivers do not have labels causing certain gets to crash in ADAR1000 class.
Fixes #122 
This has been tested with the ADAR1000 eval board and a board with devices without labels (ADRV9361-Z7035).
* Hardware: ADAR1000-EVAL, ADRV9361-Z7035+FMC Carrier
> ADAR1000 fixes

- .github/workflows/test.yml
Fix deploy action for pypi. It was assumed action would perform the setup.py sdist call like Travis-CI but this must be done explicitly.
> Fix github actions deploy stage

- adi/__init__.py
- adi/adrv9009.py
- adi/jesd.py
- test/test_adrv9009_p.py
Fix the optional requirement case when JESD is not needed. Everything should work when JESD (fs) is not needed.
Fixes #146 
* Hardware: ADRV9009 and PlutoSDR
> Fix dependency

- .github/workflows/test.yml
PR updates GH actions to print diffs of code during lint process to show required line changes. This was not happening before if the linter threw an error beforehand.
> Update GH action lint to print differences on errors

- test/test_ad9144_p.py
Signed-off-by: Trecia Agoylo <trecia.agoylo@analog.com>
Updated the arguments of the function on test_ad9144_p.py. There was a need for change because of incompatibility in the number of arguments after using pylibiio-test in managing the hardware.
#Fixes #155
* Hardware: fmcdaq2 on ZC706 
* OS: ADI Kuiper 2019R2 RC6
> Update arguments on ad9144 test

- test/test_adrv9009_p.py
Fix ADRV9009 test case with missing argument.
> Fix missing argument in ADRV9009 test

- requirements_dev.txt
- setup.cfg
Add bump2version tooling help create tagged releases.
> Add support for bump2version

- adi/adrv9009_zu11eg_multi.py
> Do not set LOs of dev C and D when FMComms8 is not hooked up

- adi/__init__.py
- adi/adar1000.py
- adi/ltc2314_14.py
- adi/one_bit_adc_dac.py
- doc/source/devices/adi.ltc2314_14.rst
- doc/source/devices/adi.one_bit_adc_dac.rst
- doc/source/devices/index.rst
- examples/adar1000_array_example.py
- examples/adar1000_single_example.py
- Add missing ADAR1000 attributes
- Add more properties & methods for control of an array as a single entity (attenuators, gains, phases, steering, etc.)
- Nest adar1000_channel class under adar1000 to allow for simpler access to the elements in the array (can be accessed via element number in the array class, or from the parent ADAR1000 object)
- Add support for LTC2314-14
- Add LTC2314-14 and one_bit_adc_dac to the documentation
> Big (hopefully final) ADAR1000 update

- adi/adrv9002.py
- adi/obs.py
- setup.py
- test/dma_tests.py
- test/test_adrv9002_p.py
This PR address some issues with the split DMA case on ADRV9002. DDSs and TX pointers were getting duplicated causing all data to go to TX2.
New test cases have been added to specifically handle split DMA
* Hardware: ADRV9002+ZCU102
> ADRV9002 split DMA fixes

- adi/__init__.py
- adi/ad9081.py
- adi/ad9081_mc.py
- adi/attribute.py
- doc/source/devices/adi.ad9081_mc.rst
- doc/source/devices/index.rst
This PR adds support for multi-AD9081 instances. This will eventually be expanded to support other devices like ADRV9009.
Internal test suite run without issue.
* Hardware: AD9081-FMC+ZCU102
Doc was added to explain to multi-AD9081 API.
> Add multi-AD9081 class support with doc

- adi/adxrs290.py
- doc/source/devices/adi.adxrs290.rst
- doc/source/devices/index.rst
- examples/adxrs290.py
- examples/requirements_adiplot.txt
This is the ADXRS290 support for the Pyadi-iio. This support includes an example which can be use with the serial backend assuming that the serial uri is correctly set. The serial backend support for the adxrs290 has been tested to work with libiio starting with 0.21 
The feature has been verified by running the examples on both adxrs290 attached to the ADICUP3029 and Raspberry pi.
- [ X] Change the URI in the example to use the uri of the actual device. Then run the example. The example should show a realtime plot. The X and Y should respond to the motion of the ADXRS290.
* Hardware: ADICUP3029 +EVAL-ADXRS290-PMDZ and Raspberry PI 3B + EVAL-ADXRS290-PMDZ
* OS: Windows 10
The documentation for the ADXRS290 has been …
> Adxrs290 support

- .pre-commit-config.yaml
- examples/QuadMxFE_example.py
This example requires the external calibration board attached, in order
to loop the Combined Tx Channels Back Into Combined Rx Path.
One TX is configured to generate a single tone of fsamp/50.
Then we enable the first Rx channel of each MxFE and, use the first
as reference and compute the phase offset between the remaining MxFEs.
Between runs the all MxFEs are resynced and the JESD links are brought
up and down. The expected result is a deterministic phase offset
between iterations and runs.
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
> examples/QuadMxFE_example: Add QuadMxFE Example

- adi/ad7606.py
- doc/source/devices/adi.ad7606.rst
- doc/source/devices/index.rst
- examples/ad7606.py
- supported_parts.md
- test/test_ad7606.py
Signed-off-by: mahphalke <Mahesh.Phalke@analog.com>
1) Added supported device and channel attributes through adi/ad7606.py file.
Reference: https://wiki.analog.com/resources/tools-software/linux-drivers/iio-adc/ad7606
2) Updated other supported files (example/ad7606.py, .rst, etc).
The code was tested with ARM based firmware application which uses Tinyiiod libraries.
Reference: https://wiki.analog.com/resources/tools-software/product-support-software/ad7606_mbed_iio_application
* Hardware: EVAL-AD7606B-FMCZ
* OS: Windows
> Added pyadi-iio support files for AD7606 devices

- adi/ad9371.py
- adi/sshfs.py
- setup.py
- test/common.py
- test/conftest.py
- test/test_sshfs.py
It seems like on systems with dropbear as an sshserver, fs.sshfs fails to authenticate.
Using this minimal class instead lets users read files without issues.
It also allows for login with no password.
This was tested using the jesd204 status files.
```python
>>> import adi
>>> sdr = adi.ad9371(uri=hostname)
>>> print(sdr.jesd204_statuses)
{'b3000000.axi-ad9371-jesd204-tx': {'enabled': 'enabled', 'Measured Link Clock': '122.882 MHz', 'Reported Link Clock': '122.880 MHz', 'Lane rate': '4915.200 MHz', 'Lane rate / 40': '122.880 MHz', 'LMFC rate': '7.680 MHz', 'SYNC~': 'deasserted', 'Link status': 'DATA', 'SYSREF captured': 'Yes', 'SYSREF alignment error': 'No'}, 'b3020000.axi-ad9371-jesd204-rx': {'enabled': 'enabled', 'Measured Link Clock': …
```
> Jesd204 ad9371

- examples/adxrs290.py
Changed the mygyro.hpf_3db_frequency to 0Hz and the mygyro.lpf_3db_frequency to 480Hz according to ADXRS290's datasheet.
Signed-off-by: Hannah Rosete <Hannah.Rosete@analog.com>
> examples/adxrs290.py:: Changed the HPF's and LPF's 3dB frequencies

- adi/cn0540.py
- test/conftest.py
API update for CN0540 to use strings instead of booleans.
* Hardware: CN0549+DE10
* OS: Ubuntu 18.04 (Host). Kuiper (Embedded)
> Update CN0540 to use strings for fda_mode

- examples/ad7746.py
Add a generic example file for ad7746.
- [ x] Test A
* Hardware: ADICUP3029 + CN0552 (connected via the PMOD connector)
* OS: no-OS
```
python examples/ad7746.py 
Found device ad7746
capacitance0
raw: 31104
scale: 4.88e-07
sampling_frequency: 91
sampling_frequency_available: [91, 84, 50, 26, 16, 13, 11, 9]
calibbias: 32768
calibscale: 1.425064
capacitance0-capacitance2
raw: 10368
scale: 4.88e-07
sampling_frequency: 91
sampling_frequency_available: [91, 84, 50, 26, 16, 13, 11, 9]
calibbias: 32768
calibscale: 1.425064
capacitance1
raw: 38528
scale: …
```
> ad7746 example

- examples/cn0548_py.py
Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>
GUI-based example for the cn0548 project, using the pyadi-iio support
for AD7799.
In conjunction with: https://github.com/analogdevicesinc/EVAL-ADICUP3029/tree/master/projects/ADuCM3029_demo_cn0548
> examples: add cn0548 python script

- adi/rx_tx.py
Some fixes to the functionality to read different data type channels from the same device.
Tested with adpd188 class with all channels and timestamp enabled, channels 0, 1 and timestamp enabled and channels 0, 5 and timestamp enabled. Also tested with only the data channels enabled without timestamp.
> Multi type buffer

- .github/scripts/install_libiio.sh
- adi/cn0540.py
CN0540 which uses the SPI engine will block on rx() calls if a SPI
transation is made, like an update to the sample rate after a buffer has
been created. Decorators were added to the dependent properties to reset
the buffer automatically before the writes are made.
This PR makes CN0540 easier to use.
Tested with CN0549 kit.
* Hardware: CN0540+DE10
> Add automatic handling of SPI engine state

- requirements_dev.txt
- test/conftest.py
- test/scpi.py
- test/test_fmcomms2-3_p.py
Production tests for fmcomms2/3, similar to the test profiles from iio-oscilloscope.
* Hardware: ADRV9361-ZC702
> Production tests for fmcomms 2 and 3

- requirements_prod_test.txt
- test/eeprom.py
- test/scpi.py
Signed-off-by: Ramona Alexandra Nechita <ramona.nechita@analog.com>
When running the production tests, at the end of the calibration procedure a window is prompted to introduce the serial number of the device and then eeprom is written accordingly. All functions related to the eeprom are moved to a separate file. It also includes minor fixes.
* Hardware: ADRV9361-ZC702
> Update save to eeprom functionality

- adi/fmcomms5.py
- test/test_fmcomms5_p.py
This PR includes fixes to fmcomms5 test, also added libad9361 fmcomms5 multiple chip sync function to fmcomms5 class to ensure both chips are in sync. May have to install the libad9361 python binding from the source, not yet available on pip.
Ran the test code on fmcomms5 hardware
No change is needed.
> Fmcomms5 test fixes

- .pre-commit-config.yaml
Switch pre-commit black to use python3 and not a specific python3 subversion.
> Change black language version to python3

- adi/QuadMxFE_multi.py
- adi/__init__.py
- adi/ad9081.py
- adi/ad9081_mc.py
- adi/fmcomms5.py
- examples/QuadMxFE_dual_example.py
- test/test_fmcomms5_p.py
* Add JESD204-FSM controls to ad9081 base class
* Add HMC7043 clock chip to QuadMxFE class
* Add QuadMxFE_multi class
* Add Quad_MxFE_dual_example using the QuadMxFE_multi class
Tested on HW
> adi/QuadMxFE_multi: Add Multi QuadMxFE support

- adi/adrf5720.py
Addition of hardware interface class for adrf5720 digital attenuator, compatible with adrf5730 and ad5731. This class has only one property which sets the hardwaregain value from -31.5dB to 0dB.
This is tested by setting the attenuation property to some value and checking if the value is written to the device channel hardwaregain attribute as well as checking the SPI lines.
* Hardware: rpi-adrf5720
* OS: Kuiper ADI-Kuiper-Linux 2019R2 RC11
Doc to follow.
> Add adrf5720 digital attenuator class

- test/rf/spec.py
- test/test_daq2_p.py
- test/test_daq3_p.py
spec: Add support for pure data - added lines of code on test/rf/spec.py to select the frequency on the right-hand side of the spectrum only.
test_daq2_p.py: Mirrored the manual test case and some little formatting changes
> Mirror DAQ2's, DAQ3's Manual Tests and Added Support for Pure Real Data in spec.py

- adi/jesd.py
Add better handling of JESD params. This fix handles multiple params that are all on one line like:
```
DID: 0, BID: 0, LID: 2, L: 4, SCR: 1, F: 4
K: 32, M: 8, N: 16, CS: 0, N': 16, S: 1, HD: 1
FCHK: 0x8C, CF: 0
ADJCNT: 0, PHADJ: 0, ADJDIR: 0, JESDV: 1, SUBCLASS: 1
```
With this code:
```python
import adi
j = adi.jesd("analog-2.local")
ls = j.get_all_link_statuses()
print(ls['84a90000.axi-jesd204-rx']['lane0_info'])
```
You get
```
{'Errors': '0', 'CGS state': 'DATA', 'Initial Frame Synchronization': 'Yes', 'Lane Latency': '1 Multi-frames and 28 Octets', 'Initial Lane Alignment Sequence': 'Yes', 'DID': '0', 'BID': '0', 'LID': '2', 'L': '4', 'SCR': '1', 'F': '4', 'K': '32', 'M': '8', 'N': '16', 'CS': '0', "N'": '16', 'S': '1', …
```
> Add better handling of 'other' JESD params

- adi/ad9081.py
Add some missing properties for MxFE for RX gains and some TX controls.
* Hardware: AD9081+ZCU102
> Add AD9081 Rx gains, Tx en, and DAC current API

- adi/ad9081.py
- adi/attribute.py
- examples/QuadMxFE_dual_example.py
- examples/QuadMxFE_example.py
- examples/ad9081_dma_example.py
- examples/ad9081_example.py
- test/common.py
- test/test_ad9081.py
Starting with the next API release the rx_nyquist_zone can be controlled individually per ADC.
This feature should be backwards compatible.
Tested on HW
* Hardware:
* OS:
> Ad9081 nyquist zone per adc

- test/test_ad9361_p.py
- test/test_ad9364_p.py
- test/test_fmcomms2-3_prod.py
Mirrored the manual tests for AD9361 and AD9364 from FMCOMMS2-3's and FMCOMMS4's respectively
Tested in the Test Harness
* Hardware: zynq-zed-adv7511-ad9361-fmcomms2-3. zynq-zed-adv7511-ad9364-fmcomms4
* OS: ADI-KUIPER-Linux
> Mirror AD9361's and AD9364's Manual Tests

- adi/ad9081_mc.py
Fix MxFE MC class for cases when IIO devices (not MxFEs) don't have names. 
> Add check for blank device name in MxFE classes

- test/test_adrv9002_p.py
Added a condition to skip the interface gain narrowband test if the baseband RX sample rate is greater than 1MHz. This answers the issue stated in [SDGSW-737](https://jira.analog.com/browse/SDGSW-737)
Tested and verified in the Test Harness
* Hardware: Zed + ADRV9002, ZCU102 + ADRV9002
* OS: ADI-Kuiper-Linux
> Added a condition to skip the interface gain narrowband test - ADRV9002

- adi/rx_tx.py
- doc/source/buffers/index.rst
- test/dma_tests.py
- test/test_adis16495_p.py
PR adds support for annotated rx/tx buffers (doc+test included), also selecting enabled channels with strings, and documents **rx_output_type** usage.
Fixes #290 
* Hardware: ADIS16495-3 + RPI
New doc was added and updated for address features
> Annotated buffers

- adi/ad9144.py
- test/test_daq2_p.py
Up until recently the driver always registered 4 channels.
While the upper two were dis-functional.
Now the driver registers the number of channels supported in the
HDL build. The default is 2.
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
* Hardware:
* OS:
If this is a new feature or example please mention or link any documentation. All new …
> adi/ad9144.py: Our default configuration for the AD9144/9152 is M=2

- adi/ad9081.py
- adi/ad9081_mc.py
- adi/rx_tx.py
- adi/sync_start.py
- doc/source/conf.py
- doc/source/fpga/dma_sync.mmd
- doc/source/fpga/index.rst
- doc/update_devs.py
- requirements_doc.txt
This PR fixes failing tests for AD9081 related to sync_start changes. It also moves sync_start to AD9081 only for now as it doesn't work across all designs. Finally, doc is added around sync_start in the FPGA section.
* Hardware: AD9081 Emulated
> AD9081 Sync Start Updates

- adi/__init__.py
- adi/ad4630.py
- doc/source/devices/adi.ad4630.rst
- doc/source/devices/index.rst
- examples/ad4630/ad4630_example_all_mode.py
- examples/ad4630/ad4630_example_simple_plot.py
- examples/ad4630/sin_params.py
- supported_parts.md
- test/test_ad4630.py
Added Initial support of ad4630-24 & ad4030-24. pyadi device interface, examples, device doc and hardware test was added.
Previous developer version i.e. branch ad463x(that was never added to main) did not have channel attributes and was not compatible with ad4030-24
* Hardware: Physcially Eval-ad4630 and EVal-4030 were tested to produce result equivalent to lab test/graphs.
@mthoren-adi
> Added ad4630 support

- test/test_ad9371.py
- test/test_adrv9009_p.py
- test/test_map.py
Edit the min_rssi, max_rssi, and sfdr_min values to a greater range for the affected tests in AD9371 and ADRV9009.
Omitted FMCOMMS5 from AD9361's test map to mitigate the number of skipped tests in the TH.
All of these fixes are from the test anomalies found in the recent ADI-Kuiper-Testing (Master, Dec 2021).
> TH Test fixes for FMCOMMS5, AD9371, ADRV9009

- examples/adxl355_no_os_example.py
Added new example for ADXL355 for No-OS starting from existing example adxl355_example.py.
The current example adxl355_example.py is not supported on No-OS due to missing timestamp attribute on No-OS driver and due to specific format (:.6f) for sampling frequency and hpf frequency attributes which the No-OS server is expecting.
The new example also contains acceleration axis offset setting.
**Test Configuration**:No-OS IIO application server
* Hardware:SDP-K1 with EVAL-ADXL355-PMDZ
* OS: No-OS project example: https://github.com/analogdevicesinc/no-OS/tree/master/projects/eval-adxl355-pmdz
Test Documentation is available here:
https://wiki.analog.com/resources/eval/user-guides/eval-adxl355-pmdz/no-os-setup
> Add example for ADXL355 for No-OS

- adi/adis16495.py
- adi/adis16507.py
- adi/adxl345.py
- adi/adxl355.py
- adi/adxrs290.py
- adi/cn0540.py
- adi/ltc2983.py
- requirements.txt
- setup.py
Numpy 1.20 deprecated built-in equivalent types which now generates
warnings. This change removes those np specific built-in and updates
required numpy to this requirement.
Ref: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> Fixed numpy deprecation warnings

- adi/__init__.py
- adi/ad4130.py
- doc/source/devices/adi.ad4130.rst
- doc/source/devices/index.rst
- examples/ad4130_example.py
- supported_parts.md
- test/test_ad4130.py
1. Added ad4130.py class file, which includes supported devices list (ad4130-8) and basic attributes (raw, offset, scale).
2. Added ad4130 example script.
3. Added other supporting files.
Signed-off-by: MPhalke <mahesh.phalke@analog.com>
Added support for ad4130 device
* Hardware: SDP-K1, AD4130 EVB
* OS: Windows
> Added support for ad4130 device

- adi/ad7689.py
Renamed '_channels' to 'channels' in ad7689.py file due to recent updates in the libiio
Signed-off-by: MPhalke <mahesh.phalke@analog.com>
Issue fixed in adi/ad7689.py file at line number 76.
* Hardware: SDP-K1, AD7689 EVB
* OS: Windows
> ad7689: Corrected the 'channels' attribute name

- requirements_prod_test.txt
When running "pip install -r requirements_prod_test.txt" an error pops
up:
"ERROR: Could not find a version that satisfies the requirement
tkinter".
Use proper name for the library so the requirements doc can be fully
used with pip.
run command: `pip install -r requirements_prod_test.txt`
Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>
> requirements_prod_test: fix tkinter library

- examples/ad9172.py
- test/test_map.py
Signed-off-by: Hannah Rosete <Hannah.Rosete@analog.com>
This commit is originally from PR #333. This is to add the support for AD9172 and separate it from the PR that contains support for FMCOMMS11. This will add an example for AD9172 and add its project on the test_map.py
Tested on the <project_name> installed on the Test Hatrness:
- [Hardware Tests/HW_pyadi_test/215](http://10.116.171.86/jenkins/blue/organizations/jenkins/HW_tests%2FHW_pyadi_test/detail/HW_pyadi_test/215/pipeline)
> Add support for AD9172

- test/test_ad9081.py
- test/test_map.py
- 2915285 - Add AD9081 projects to the test_map for them to be tested on the Test Harness
- 9235963 - Omitted FMComms5's appended key to AD9361 even though it was commented (for code consistency)
Fixes [this issue in JSL PR.](https://github.com/sdgtt/jenkins-shared-library/pull/52)
[jenkins / HW_tests/HW_pyadi_test / HW_pyadi_test / #225](http://10.116.171.86/jenkins/blue/organizations/jenkins/HW_tests%2FHW_pyadi_test/detail/HW_pyadi_test/225/pipeline/1531/)
> Add AD9081 projects to the test_map

- test/dma_tests.py
dma_rx passes as long as there's at least one nonzero data point. Using np.sum(np.max(data)) can overflow to a negative value, particularly with high-resolution ADCs and long buffers, failing the test. Replace with np.max(np.abs(data))
Signed-off-by: Mark Thoren <mark.thoren@analog.com>
Fix DMA test issue where large values can roll over to a negative sum, failing the test.
Test fails with an actual LTC2387-18 if you apply a large input signal +4.0V or -4.0V)
dma_test() exercised by intercepting data returned by rx_tx.py's rx() method, returning test vectors.
* Hardware: CN0577 / LTC2387-18 board, with data intercepted in rx_tx.py
* OS: ADI Kuiper Linux on ZedBoard, tests running on Windows 10.
> Fix dma_rx test overflow issue.

- test/test_map.py
This PR adds the following supported projects, as of now, in PyADI-IIO:
- DAQ3
- DAQ2
- ADRV9371
- ADRV9375
- ADRV9009
- ADRV9009-ZU11EG
- FMCOMMS8
- ADRV9002
- AD9081
- AD9083
- AD9136
- AD9265
- AD9434
- AD9739A
- FMCJESDADC1
- AD4020
- AD4630
- AD9467
- ADAQ8092
- AD9361
- AD9364
- AD9625
Microblaze and no-OS projects were also added to the roster to be able to cater to the ongoing Jenkins pipeline support for the two.
This also futureproofs the tests of the projects that are yet to be added to the Test Harness.
AI: Add these projects' list of IIO devices in pytest-libiio, specifically in the [adi_hardware_map.py](https://github.com/tfcollins/pytest-libiio/blob/master/pytest_libiio/resources/adi_hardware_map.yml)
@tfcollins
> Add list of supported projects in test_map.py

- doc/source/conf.py
Fix sphinx-favicon package which has a name change in 1.0: https://github.com/tcmetzger/sphinx-favicon/blob/v1.0/README.md
> [FIX] Update favicon usage in doc with package update in 1.0

- adi/max31855.py
The IIO device name for the MAX31855 is "maxim_thermocouple" in both Linux and no-OS.
The IIO device's name for the MAX31855 (in both no-OS(after a recent update) and Linux) is "maxim_thermocouple". This requires a rename here too.
**Test Configuration**: MCU running the MAX31855 no-OS IIO example
* Hardware: MAX32655 + FTHR to PMOD adapter + MAX31855
* OS: Linux
> MAX31855: Fix the device's name

- adi/cn0511.py
- examples/cn0511_example.py
- added attribute for cn0511 to check if the board was calibrated or not (cn0511.py)
- added use of this attribute in cn0511_example.py
- depends on https://github.com/analogdevicesinc/libad9166-iio/pull/16
#Issue
- cn0511 was returning a segmentation error when used as normal (iio-oscilloscope or pyadi-iio example) if it was not calibrated in production.
-  New feature (non-breaking change which adds functionality)
- Tested if this attribute affects cn0511 output with a spectrum analyzer on 2 boards, one calibrated and one uncalibrated.
OBS: the calibration here is referring to running the production test for cn0511 with success.
-  My code follows the style guidelines of this project
-  I have performed a self-review of my own code
-  I have commented my code, particularly in …
> Fix seg fault v2

- test/test_ad9361_p.py
This PR is to fix assertion errors in test_ad9361 to match zc702-fmcomms3 performance. 
> test: Fix assertion errors to match zc702-fmcomms3 performance

- adi/rx_tx.py
To enable buffer transmission with data types larger than 16 bits.
This change extends support to transmit data to DACs with more than 16-bit precision.
> rx_tx: Add tx_data_type

- test/test_adrv9002_p.py
This PR includes a fix to an existing failing test in adrv9002.
>FAILED test/test_adrv9002_p.py::test_adrv9002_hardware_gain
>  Failed to set: tx_hardwaregain_chan0
> Set: -22.700000000000003
> Got: -22.7
> fix: random_values_in_range in test_adrv9002

- test/attr_tests.py
- test/conftest.py
- test/test_ad4630.py
- test/test_ad5754r.py
- test/test_ad7768.py
- test/test_ad7768_4.py
- test/test_ad9081.py
- test/test_ad9084.py
- test/test_adl5240.py
- test/test_adrv9002_p.py
- test/test_cn0575.py
- test/test_cn0579.py
This replaces the misspelled "multipe" with "multiple" in the tests.
CI
> test: fix spelling of multiple

- adi/rx_tx.py
As mentioned in the doc string and in the setter type hints, `rx_enabled_channels` can be either a list of channel numbers (int) or names (str).
* Hardware:
* OS:
> adi/rx_tx.py: fix return type of rx_enabled_channels

- test/attr_tests.py
Since Python objects will dynamically add an attribute if one does not exist when calling `setattr()`, we need to check that the attribute actually exists before setting it. Otherwise, tests will pass even if the attribute is not defined in the object being tested.
While developing #474, I noticed that tests were passing when I had an obvious mistake. Applying this fix caught the mistake.
> test/attr_tests: fix tests with setattr

- test/test_adrv9002_p.py
This PR includes small change on the profile test of adrv9002. The 'profile' property will fail in hasattr() check since it has no getter. In the test, changed 'profile' to 'write_profile', directly using the write_profile attribute. All profile test passed.
- Run the tests on both zed-adrv9002 and zcu102-adrv9002 on all variants.
* Hardware:
* OS:
* 
> test: update adrv9002 profile test

- adi/__init__.py
- adi/ad2s1210.py
- doc/source/devices/adi.ad2s1210.rst
- doc/source/devices/index.rst
- supported_parts.md
- test/emu/devices/ad2s1210.xml
- test/emu/hardware_map.yml
- test/test_ad2s1210.py
- test/test_adrv9002_p.py
> Update PRs into master back to main

- adi/rx_tx.py
Use equation (raw+offset)*scale for IIO property conversion
Fix conversion equation for SI conversion
* Hardware:
* OS:
> Update SI converstion

- .github/scripts/install_libiio.sh
- .github/scripts/install_part_libs.sh
- .github/scripts/install_pydeps.sh
- .github/workflows/test.yml
- adi/compat.py
- adi/rx_tx.py
- doc/source/libiio.md
- doc/update_devs.py
- requirements_dev.txt
This PR adds a compatibility layer to support libiio v0.X and v1.X. It includes:
- Attribute support
- Buffer support
- Basic CI infrastructure
- Doc notes
iio-emu support appears broken at this time so its not enabled in CI yet.
> Add libiio v1.X support

- adi/ad4110.py
- adi/ad4130.py
- adi/ad469x.py
- adi/ad4858.py
- adi/ad5686.py
- adi/ad5754r.py
- adi/ad578x.py
- adi/ad5940.py
- adi/ad717x.py
- adi/ad719x.py
- adi/ad7606.py
- adi/ad7689.py
- adi/ad7746.py
- adi/ad7768.py
- adi/ad777x.py
- adi/ad7799.py
- adi/ad9083.py
- adi/ad9172.py
- adi/adaq8092.py
- adi/adpd1080.py
- adi/adpd188.py
- adi/adpd410x.py
- adi/ltc2499.py
- adi/ltc2983.py
- adi/max11205.py
- adi/max14001.py
- adi/max9611.py
A large set of classes were not reseting their channel names during their init. This will create undesired behavior since _rx/tx_channel_names are class properties and shared across all instances
> Fix dynamic channel config classes

- test/dma_tests.py
- test/test_ad7768.py
- test/test_ad7768_4.py
This PR includes changes on ad7768 and ad7768-4 tests which enables setting the filter_type first before testing the rx buffer. With that, a change in dma_rx test was introduced, adding param_set to enable setting of attributes firsts before getting data from buffer. If param_set is not passed, it will still work the usual.
For ad7768/ad7768-4, this test ensures that for both filter types the buffer is still working.
- [] This change requires a documentation update
If this is a new feature or example please mention or link any documentation. All new hardware interface classes …
> Update ad7768/ad7768-4 tests

- adi/rx_tx.py
This PR includes a change in rx_tx class in tx() method which interchanges if conditions for tx_enabled_channels and tx_data_type to check if there are tx_enabled_channels before accessing them. The fix was found due to a failed test in test_pluto_p.py, which is the test_loopback_zeros or dma_dac_zeros in dma_tests. The issue is caused by tx_enabled_channels being accessed in tx() method while it is set to None.
* Hardware: ADALM-Pluto
* OS: Windows
If this is a new feature or example please mention or link any documentation. All new …
> Fix tx_enabled_channel condition order

- test/test_ad9081.py
AD9081 tests started to fail recently across all variants on zcu102. They channel parameter does not get scaled according to the available channels. The issue was handled by checking for tx channel names and getting the channel index from the list, even if the test should check for rx channels.
* Hardware: zcu102-ad9081, all variants
* OS: Tests were run on Windows
> test: ad9081: Scale channel param

- adi/cn0532.py
Add whitespace around arithmetic operators so that the cn0532 module doesn't trigger flake8 failures on other runs.
Tiny cleanup by adding whitespace around arithmetic operators in cn0532.py. The flake8 check in pre-commit was reporting an issue here while I was working on #524 
Re-ran `pre-commit run --all-files` after the change to make sure the test passed.
* OS: Fedora 39, Python 3.12, virtualenv with pyadi-iio requirements from requirements_prod_test.txt installed.
> cn0532.py: clean up for flake8 whitespace check

- adi/__init__.py
- adi/adf4159.py
- adi/tddn.py
- doc/source/devices/adi.tddn.rst
- doc/source/devices/index.rst
- examples/pluto_tddn.py
Adding support for TDDN:
- Added tddn.py in library
- Added pluto_tddn.py example script
- Updated the documentation to include the TDDN
The example script was tested on Pluto in Phaser mode. The TDD configuration and functionality from pluto_tddn.py example was validated and tested with an oscilloscope.
TDDN wiki page: https://wiki.analog.com/resources/fpga/docs/axi_tdd
> Add support for Generic TDD Engine (TDDN)

- adi/ad7124.py
- examples/ad7124.py
This PR includes fix of the ad7124 class. When using .name, it cannot list the channels thus changing to .id in getting the channels. Also updated the example.
> AD7124 fix

- test/test_map.py
zcu102-ad9081-204b-txmode9-rxmode4 skips all tests because of the missing typo in test_map.py
> Fix typo: Missing comma skipping tests for 204b variant

- adi/adis16475.py
- test/test_adis16475_p.py
Set default trigger for adis16475 driver
* Hardware:
* OS:
> adi: adis16475: Set default trigger

- test/test_cn0579.py
This change modifies the available sampling frequency being set by removing some values that are not being displayed in cn0579 iio_info. The fix was done due to the ValueError caused by setting sampling frequencies which are not supported.  
* Hardware:
* OS:
> Fix cn0579 test

- adi/ad9081.py
- test/attr_tests.py
- test/conftest.py
- test/dma_tests.py
- test/rf/spec.py
- test/test_ad9081.py
Fixes
test/test_ad9081.py::test_ad9081_iq_loopback fails for variants with different sampling_frequency between rx and tx device. With these modifications, the estimated frequency at rx is within tolerance, although some tests still fail because of peak value assertions.
* Hardware:
* OS:
> Ad9081 test fixes

- .github/workflows/test.yml
This repo stores different versions of the doc into multiple directories of the gh-pages branch.
Due to this, links requiring to reach the website root (not the content root of the doc itself), are broken if the deploy directory is different than `./` (e.g. `./main`, `./prs/1234`)
To resolve this issue, the ADOC_TARGET_DEPTH  env variable was implemented https://github.com/analogdevicesinc/doctools/commit/1da4cf161e515f1bd17aa102dbc25e42089f654a to allow tuning the depth before the doc build. 
Example of ADOC_TARGET_DEPTH values:
* ./         : ../       (0 or unset)
* ./main/    : ../../    (1)
* ./prs/1234 : ../../../ (2)
On Doctools I also added [a snipped to generate a JSON with the tags/branches/prs of the build docs](https://github.com/analogdevicesinc/doctools/blob/main/.github/work …
> .github: Add destination depth to doc build

- test/attr_tests.py
- test/conftest.py
- test/test_cn0540.py
This update includes a class for cn0540 test and a new attribute test. 
* Hardware:
* OS:
> Add cn0540 test

- pyproject.toml
Fixed typo in GitHub URL which causes broken links on PyPI, etc.
- [ Y ] Bug fix (non-breaking change which fixes an issue)
URL now takes you to this repo.
Not applicable.
- [ NA ] My code follows the style guidelines of this project
- [ NA ] I have performed a self-review of my own code
- [ NA ] I have commented my code, particularly in hard-to-understand areas
- [ Y ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ NA ] I have made corresponding changes to the documentation
- [ NA ] My changes generate no new warnings
- [ NA ] I have added tests that prove my fix is effective or that my feature works
- [ NA ] New and existing unit tests pass locally with my changes
- [ NA ] Any dependent changes have been merged and published in downstream modules
> URL fix in pyproject.toml metadata

- adi/obs.py
Fix issue related to new complex data configuration flags for obs TX path.
> Update TX OBS to use new complex data flags

- examples/pluto_tddn.py
This example was updated to transmit a sine wave and capture 100 data buffers, all synchronized by the TDDN.
* Hardware: Pluto Rev. D 
* OS: Windows 10
> examples/pluto_tddn: Add a complete example

- adi/ad9083.py
- adi/ad9467.py
AD9083 tests because of index error. AD9467 only has one channel.
> Class fixes after rc testing

- test/conftest.py
The update includes adding pytest hooks in conftest.py to enable adding of custom properties to the test report. The additional properties are comprised of the exception type and failure message, and description (docstring) of failing tests.
* Hardware:
* OS:
> Update conftest.py 

- examples/phaser/phaser_prod_tst.py
Minor adjustment - lower RX LO to improve yield.
* Hardware:
* OS: ADI Kuiper Linux
> Adjust RX LO frequency for better yield.

- test/dma_tests.py
- test/rf/spec.py
- test/test_daq2_p.py
- test/test_daq3_p.py
daq2/3 consistently fails on at the lowest scale param 0.06. The minimum peak values are empirically set using test harness hardware.
* Hardware: zcu102-fmcdaq3
* OS: Kuiper
> test: modiy daq2/3 assertions based on scale

- doc/source/dev/index.rst
- doc/source/dev/test_jesd.rst
- test/common.py
- test/conftest.py
- test/jesd_tests.py
- test/test_adrv9009_zu11eg.py
Add common fixtures to verify JESD204 links. This reuses the JESD classes so the use of SSHFS or libiio for attribute collection should be handled by pyadi-iio itself and not this test.
* Hardware: ADRV9009-ZU11EG
* OS: Ubuntu 22.04
See new doc pages
> Add JESD specific test fixtures

- adi/context_manager.py
- test/common.py
In the case of usb connections, no two iio.Context objects can exist at the same time. When the `dev_interface` functions are called inside the test functions, the function may fail before the `del sdr` operation can be performed and the iio.Context object is not destroyed. The next test that calls the `dev_interface` function will therefore also fail (since it cannot create another iio.Context object).
By transforming the `context_manager` class into a Pythonic context manager, we make use of the `with` statement. The `with` block will act as a wrapper over the usage of iio.Context objects and it will ensure that when errors are thrown, they are logged and memory is properly freed.
`context_manager` objects can still be created without the `with` statement (introduced change doesn't …
> context_manager.py: Fix error handling for usb

- adi/ad9081.py
- adi/ad9081_mc.py
Some attributes are fetched from the first channel, and if multichip, from the first device:
* ad9081: [...]
* ad9081_mc: {'dev1': [...], 'dev2': [...],}
Due to the type change, examples/QuadMxFE_dual_example.py was broken.
Use the method overwrite to fix the type and behavior.
* Hardware:
* OS:
> ad9081/_mc: fix type and first channel defaulting

- test/test_ad9172_p.py
- test/test_ad9361_p.py
Disable random tests that fail and are not repeatable
> Skip GH tests failing as there they are not repeated offline

- .github/workflows/doc.yml
- doc/Makefile
Make's -j flag is not passed to sphinx, so default SPHINXOPTS to
-j auto.
Make's -j flag is not passed to sphinx, so default SPHINXOPTS to
-j auto.
* Hardware:
* OS:
> docs: Makefile: Default to parallel build 

- adi/adxl355.py
Set rx_data_type to 32-bit integer. Not sure where the mismatch crept in, I suspect an earlier version of rx() either detected, or tolerated, the ADXL355's 20-bit data.
* Hardware: EVAL-ADXL355-PMDZ on Raspberry Pi
* OS: Windows on remote host, Raspberry Pi on local
N/A
> Set _rx_data_type to 32-bits

- adi/ad719x.py
Fix the lint build by adding the missing whitespace after ','.
Fixes: https://github.com/analogdevicesinc/pyadi-iio/commit/33aeb03c3f0e13693ee24ede2d78079a2adcce61 ("projects:ad7191_iio:Added the python support for ad7191")
> adi: ad719x: add missing whitespace in array

- .github/workflows/test.yml
Azure VM seem to have IIO running in their kernel now which breaks how our emulation tests work. Disable scanning fixes this issue
> Remove scanning from emu tests
